# Generated by Django 3.2.9 on 2022-09-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='complete',
        ),
    ]
